development:
  adapter: mysql2
  database: bmi_development
  host: localhost
  username: aio
  password: aioa10aioa10

test:
  adapter: mysql2
  database: bmi_test
  host: localhost
  username: 123
  password: 123

production:
  adapter: mysql2
  database: bmi_production
  host: localhost
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  
