development:
  adapter: mysql
  database: bmi_development
  host: localhost  
  username: bmi
  password: down293
  
test: &test
  adapter: mysql
  database: bmi_test
  host: localhost
  username: bmi
  password: down293

production:
  adapter: mysql
  database: bmi_production
  host: localhost
  username: bmi
  password: down393

cucumber:
  <<: *test